package com.nowait.model;

public enum AcaoAuditoria {
    LOGIN_SUCESSO,
    LOGIN_FALHA,
    REGISTRO_CONTA,
    SENHA_RESET_SOLICITADO,
    SENHA_REDEFINIDA,

    FILA_ENTRADA,
    FILA_CHAMADA,
    FILA_CHAMADA_AUTOMATICA,
    FILA_ATENDIMENTO,
    FILA_CANCELAMENTO,

    AGENDAMENTO_CRIADO,
    AGENDAMENTO_CANCELADO,
    AGENDAMENTO_CONFIRMADO,
    AGENDAMENTO_EXPIRADO,

    MESA_CRIADA,
    MESA_STATUS_ALTERADO,
    MESA_LIBERADA,
    MESA_REMOVIDA,

    ADMIN_USUARIO_REMOVIDO
}
